version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: "Running unit tests"
          command: npm run test-unit
      - run:
          name: "Running build command"
          command: npm run build

workflows:
  test_my_app:
    jobs:
      - build_and_test
